### ISSUE TITLE
Internal server error when clicking subscribe button

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#49] opened 2023-06-18 16:34 UTC
I clicked the "subscribe" button that sits underneath the update profile button and got an internal server error. I've tried clicking the button multiple times.

<img width="530" alt="Screenshot 2023-06-18 at 9 30 57 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/bde7db0a-c191-47b0-8276-4f4749e3fe55">

## Reproduction steps

* Log in to dashboard.
* Click "Subscribe" button in profile dashboard.
* Browser redirects to `/api/subscribe-to-dlcm`
* Console shows a `500` status response from the server.

**Comment by frankmarra** [comment] 2023-06-19 00:00
This is being caused by RLS. Have to research a workaround, but for now, RLS is disabled.

**Comment by frankmarra** [comment] 2023-06-22 04:23
Fixed in next PR

**Closed as completed by frankmarra** 2023-06-22 04:23 UTC
Labels: bug
